# Generated by Django 5.1.15 on 2026-07-25 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create_account', '创建账号'), ('enable_account', '启用账号'), ('disable_account', '停用账号'), ('change_role', '变更角色'), ('reset_password', '重置密码'), ('force_change_password', '强制改密'), ('update_profile', '更新资料')], max_length=30, verbose_name='操作类型')),
                ('detail', models.JSONField(default=dict, verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('result', models.CharField(default='success', max_length=20, verbose_name='操作结果')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_operator', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色编码')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统内置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('modules', models.ManyToManyField(blank=True, related_name='roles', to='modules.module', verbose_name='可访问模块')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='显示名称')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='首次登录强制改密')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='上次改密时间')),
                ('notify_account_security', models.BooleanField(default=True, verbose_name='账号与安全通知')),
                ('notify_permission_change', models.BooleanField(default=True, verbose_name='权限变更通知')),
                ('notify_module_activity', models.BooleanField(default=True, verbose_name='模块动态通知')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
