# Generated by Django 5.1.15 on 2026-06-13 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='项目配置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_projects',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(verbose_name='序号')),
                ('description', models.TextField(blank=True, default='', verbose_name='分镜描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='镜头配置')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='story.project')),
            ],
            options={
                'db_table': 'story_shots',
                'ordering': ['project', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('story_outline', '剧情整理'), ('storyboard', '分镜脚本'), ('image_generation', '图片生成'), ('video_generation', '视频生成'), ('voice_generation', '配音生成')], max_length=30, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='输出数据')),
                ('attempt', models.PositiveSmallIntegerField(default=1, verbose_name='尝试次数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='story.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='story.project')),
                ('shot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='story.shot')),
            ],
            options={
                'db_table': 'story_jobs',
                'ordering': ['project', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('audio', '音频'), ('subtitle', '字幕')], max_length=20, verbose_name='素材类型')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '失败'), ('stale', '待更新'), ('outdated', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('is_stale', models.BooleanField(default=False, verbose_name='是否待更新')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('outdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_assets', to='story.asset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='story.project')),
                ('shot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='story.shot')),
            ],
            options={
                'db_table': 'story_assets',
                'ordering': ['project', 'shot', 'asset_type', '-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-updated_at'], name='story_proje_user_id_b9ad2b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status'], name='story_proje_user_id_3e295e_idx'),
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['project', 'order'], name='story_shots_project_bc7283_idx'),
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['project', 'status'], name='story_shots_project_d3c04a_idx'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='uq_shot_project_order'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['project', 'job_type'], name='story_jobs_project_5ba1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['shot', 'job_type'], name='story_jobs_shot_id_ea3fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['project', 'status'], name='story_jobs_project_fe63a1_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['project', 'job_type', 'status'], name='story_jobs_project_591d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'asset_type'], name='story_asset_project_e0476a_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['shot', 'asset_type'], name='story_asset_shot_id_8a0d16_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'is_stale'], name='story_asset_project_341056_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'status'], name='story_asset_project_5d90cd_idx'),
        ),
    ]
