# Generated by Django 5.1.15 on 2026-07-25 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模块编码')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('description', models.TextField(blank=True, verbose_name='模块描述')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='图标标识')),
                ('status', models.CharField(default='ready', max_length=20, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '业务模块',
                'verbose_name_plural': '业务模块',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserModuleAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_authorizations', to='modules.module', verbose_name='模块')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户模块授权',
                'verbose_name_plural': '用户模块授权',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
