# Generated by Django 5.1.15 on 2026-07-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermoduleauthorization',
            options={'ordering': ['-granted_at'], 'verbose_name': '用户模块授权（已废弃）', 'verbose_name_plural': '用户模块授权（已废弃）'},
        ),
    ]
